SELECT
    po.SUPPLIER_ID,
    sup.SUPPLIER_NAME,
    po.PRODUCT_ID,
    p.PRODUCT_NAME,
    COUNT(*) AS TOTAL_ORDERS,
    SUM(po.QUANTITY_ORDERED) AS TOTAL_UNITS_ORDERED,
    SUM(po.TOTAL_COST) AS TOTAL_SPEND,
    AVG(
        CASE
            WHEN po.STATUS = 'DELIVERED' AND po.ACTUAL_DELIVERY_DATE IS NOT NULL
            THEN DATEDIFF('day', po.EXPECTED_DELIVERY_DATE, po.ACTUAL_DELIVERY_DATE)
        END
    ) AS AVG_DELIVERY_DELAY_DAYS,
    ROUND(
        100.0 * SUM(
            CASE
                WHEN po.STATUS = 'DELIVERED' AND po.ACTUAL_DELIVERY_DATE <= po.EXPECTED_DELIVERY_DATE
                THEN 1 ELSE 0
            END
        ) / NULLIF(SUM(CASE WHEN po.STATUS = 'DELIVERED' THEN 1 ELSE 0 END), 0),
        2
    ) AS ON_TIME_DELIVERY_RATE,
    SUM(CASE WHEN po.STATUS = 'CANCELLED' THEN 1 ELSE 0 END) AS CANCELLED_ORDER_COUNT
FROM {{ ref('stg_purchase_orders') }} po
INNER JOIN {{ ref('stg_suppliers') }} sup ON po.SUPPLIER_ID = sup.SUPPLIER_ID
INNER JOIN {{ ref('stg_products') }} p ON po.PRODUCT_ID = p.PRODUCT_ID
GROUP BY po.SUPPLIER_ID, sup.SUPPLIER_NAME, po.PRODUCT_ID, p.PRODUCT_NAME
