------------------------------------------------------------
-- Step 2: Load Synthetic Data into Snowflake
------------------------------------------------------------

USE DATABASE FROSTBYTE_DB;
USE SCHEMA RAW;
USE WAREHOUSE FROSTBYTE_XS_WH;

-- File format
CREATE OR REPLACE FILE FORMAT FROSTBYTE_CSV_FF
  TYPE = 'CSV'
  SKIP_HEADER = 1
  FIELD_OPTIONALLY_ENCLOSED_BY = '"'
  NULL_IF = ('');

-- Internal stage
CREATE OR REPLACE STAGE FROSTBYTE_LOAD_STG
  FILE_FORMAT = FROSTBYTE_CSV_FF;

-- Tables
CREATE OR REPLACE TABLE STORES (
    STORE_ID VARCHAR,
    STORE_NAME VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    SALES_REGION VARCHAR,
    STORE_TIER VARCHAR,
    OPENED_DATE DATE,
    SQUARE_METRES INTEGER,
    IS_ACTIVE BOOLEAN
);

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR,
    PRODUCT_NAME VARCHAR,
    CATEGORY VARCHAR,
    CATEGORY_CODE VARCHAR,
    UNIT_COST NUMBER(10,2),
    UNIT_PRICE NUMBER(10,2),
    SUPPLIER_ID VARCHAR,
    WEIGHT_KG NUMBER(10,2),
    IS_ACTIVE BOOLEAN
);

CREATE OR REPLACE TABLE SUPPLIERS (
    SUPPLIER_ID VARCHAR,
    SUPPLIER_NAME VARCHAR,
    CONTACT_EMAIL VARCHAR,
    PHONE VARCHAR,
    CITY VARCHAR,
    STATE VARCHAR,
    COUNTRY VARCHAR,
    LEAD_TIME_DAYS INTEGER
);

CREATE OR REPLACE TABLE STOCK_LEVELS (
    STOCK_LEVEL_ID VARCHAR,
    STORE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    QUANTITY_ON_HAND INTEGER,
    REORDER_POINT INTEGER,
    REORDER_QUANTITY INTEGER,
    LAST_COUNTED_DATE DATE,
    IS_BELOW_REORDER BOOLEAN
);

CREATE OR REPLACE TABLE PURCHASE_ORDERS (
    PO_ID VARCHAR,
    STORE_ID VARCHAR,
    PRODUCT_ID VARCHAR,
    SUPPLIER_ID VARCHAR,
    QUANTITY_ORDERED INTEGER,
    UNIT_COST NUMBER(10,2),
    TOTAL_COST NUMBER(12,2),
    ORDER_DATE DATE,
    EXPECTED_DELIVERY_DATE DATE,
    ACTUAL_DELIVERY_DATE DATE,
    STATUS VARCHAR
);

-- PUT files to stage (run from SnowSQL or CoCo)
PUT file://stores.csv @FROSTBYTE_LOAD_STG/stores AUTO_COMPRESS=TRUE;
PUT file://suppliers.csv @FROSTBYTE_LOAD_STG/suppliers AUTO_COMPRESS=TRUE;
PUT file://products.csv @FROSTBYTE_LOAD_STG/products AUTO_COMPRESS=TRUE;
PUT file://stock_levels.csv @FROSTBYTE_LOAD_STG/stock_levels AUTO_COMPRESS=TRUE;
PUT file://purchase_orders.csv @FROSTBYTE_LOAD_STG/purchase_orders AUTO_COMPRESS=TRUE;

-- COPY INTO tables
COPY INTO STORES FROM @FROSTBYTE_LOAD_STG/stores;
COPY INTO SUPPLIERS FROM @FROSTBYTE_LOAD_STG/suppliers;
COPY INTO PRODUCTS FROM @FROSTBYTE_LOAD_STG/products;
COPY INTO STOCK_LEVELS FROM @FROSTBYTE_LOAD_STG/stock_levels;
COPY INTO PURCHASE_ORDERS FROM @FROSTBYTE_LOAD_STG/purchase_orders;
