------------------------------------------------------------
-- Step 1: Frostbyte Infrastructure Setup
------------------------------------------------------------

-- Database
CREATE DATABASE IF NOT EXISTS FROSTBYTE_DB;

-- Schemas (medallion architecture)
CREATE SCHEMA IF NOT EXISTS FROSTBYTE_DB.RAW;
CREATE SCHEMA IF NOT EXISTS FROSTBYTE_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS FROSTBYTE_DB.MARTS;

-- Warehouse
CREATE WAREHOUSE IF NOT EXISTS FROSTBYTE_XS_WH
  WITH WAREHOUSE_SIZE = 'XSMALL'
       AUTO_SUSPEND = 60
       AUTO_RESUME = TRUE
       INITIALLY_SUSPENDED = TRUE;

-- Roles
CREATE ROLE IF NOT EXISTS FROSTBYTE_ADMIN;
CREATE ROLE IF NOT EXISTS FROSTBYTE_ANALYST;

-- Grants for FROSTBYTE_ADMIN
GRANT USAGE ON DATABASE FROSTBYTE_DB TO ROLE FROSTBYTE_ADMIN;
GRANT USAGE ON ALL SCHEMAS IN DATABASE FROSTBYTE_DB TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE TABLE ON SCHEMA FROSTBYTE_DB.RAW TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE TABLE ON SCHEMA FROSTBYTE_DB.STAGING TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE TABLE ON SCHEMA FROSTBYTE_DB.MARTS TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE VIEW ON SCHEMA FROSTBYTE_DB.RAW TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE VIEW ON SCHEMA FROSTBYTE_DB.STAGING TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE VIEW ON SCHEMA FROSTBYTE_DB.MARTS TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE STAGE ON SCHEMA FROSTBYTE_DB.RAW TO ROLE FROSTBYTE_ADMIN;
GRANT CREATE FILE FORMAT ON SCHEMA FROSTBYTE_DB.RAW TO ROLE FROSTBYTE_ADMIN;
GRANT USAGE ON WAREHOUSE FROSTBYTE_XS_WH TO ROLE FROSTBYTE_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FROSTBYTE_DB.RAW TO ROLE FROSTBYTE_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FROSTBYTE_DB.STAGING TO ROLE FROSTBYTE_ADMIN;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA FROSTBYTE_DB.MARTS TO ROLE FROSTBYTE_ADMIN;

-- Grants for FROSTBYTE_ANALYST
GRANT USAGE ON DATABASE FROSTBYTE_DB TO ROLE FROSTBYTE_ANALYST;
GRANT USAGE ON SCHEMA FROSTBYTE_DB.MARTS TO ROLE FROSTBYTE_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA FROSTBYTE_DB.MARTS TO ROLE FROSTBYTE_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA FROSTBYTE_DB.MARTS TO ROLE FROSTBYTE_ANALYST;
GRANT USAGE ON WAREHOUSE FROSTBYTE_XS_WH TO ROLE FROSTBYTE_ANALYST;

-- Grant roles to current user (adjust as needed)
GRANT ROLE FROSTBYTE_ADMIN TO ROLE SYSADMIN;
GRANT ROLE FROSTBYTE_ANALYST TO ROLE FROSTBYTE_ADMIN;
