SELECT
    PO_ID,
    STORE_ID,
    PRODUCT_ID,
    SUPPLIER_ID,
    QUANTITY_ORDERED,
    UNIT_COST,
    TOTAL_COST,
    ORDER_DATE,
    EXPECTED_DELIVERY_DATE,
    ACTUAL_DELIVERY_DATE,
    STATUS
FROM {{ source('frostbyte_raw', 'PURCHASE_ORDERS') }}
