SELECT
    STOCK_LEVEL_ID,
    STORE_ID,
    PRODUCT_ID,
    QUANTITY_ON_HAND,
    REORDER_POINT,
    REORDER_QUANTITY,
    LAST_COUNTED_DATE,
    IS_BELOW_REORDER
FROM {{ source('frostbyte_raw', 'STOCK_LEVELS') }}
